### ISSUE TITLE
Comply with standard repositories names

### ISSUE THREAD

**Issue by pattacini** [robotology/segmentation-to-pointcloud#1]
The name of this repository is not standard. Please, make up a new one according to the policy we have: e.g. `object-3d-reconstruction`

**Comment by pattacini** [comment]
Changing merely the repository name is not sufficient, of course.
Look for any occurrence of the old tag in any file of the project.

**Comment by pattacini** [comment]
This is quite urgent @tanismar, given that it represents the entry point from the **robotology** organization.

**Comment by pattacini** [comment]
It seems you made it. :+1: 
Don't forget to close issues then.

**Comment by tanismar** [comment]
Hi .. I finished in the last minute before leaving on Friday, and I still wanted to change the name in other applications connecting to this module before closing. But thanks for checking it.
