### ISSUE TITLE
Create doxygen documentation

### ISSUE THREAD

**Issue by pattacini** [robotology/segmentation-to-pointcloud#2]
Talk to @giuliavezzani to know how to create doxygen documentation via `gh-pages` special branch.

Look at this wiki page for relative material: http://wiki.icub.org/wiki/Learning_more_about_git#Using_GitHub_Pages_and_save_space_on_repository.

**Comment by pattacini** [comment]
Also, the `README.md` file must reflect these changes, including proper sections for required dependencies.

**Comment by tanismar** [comment]
Done, link can be found here (also referenced on the readme.md): 
http://robotology.github.io/segmentation-to-pointcloud
